# Generated by Django 4.1.5 on 2023-01-24 10:46

import assignment.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=254, unique=True, validators=[assignment.web.validators.validate_length]),
        ),
    ]
